### ISSUE TITLE
No permite "eliminar" al cliente

### ISSUE THREAD

**Issue by sixfingers76** [jjosez/POS#10]
Hola, en primer lugar felicidades por el plug-in, un trabajo excelente! Quería comentar que, a la hora de hacer una venta, el plug-in siempre "obliga" a tener un cliente seleccionado, a pesar de que en las facturas simplificadas no es necesario especificar el cliente. ¿Hay alguna forma de evitar tener que seleccionar un cliente siempre?. Gracias. Un saludo.

**Comment by jjosez** [comment]
En la configuracion de las terminales, se puede asignar un cliente predeterminado, para no tener que seleccionarlo cada vez.
