### ISSUE TITLE
2 Comportamientos Anormales

### ISSUE THREAD

**Issue by lmiguelm26** [jjosez/POS#14]
1 : tengo palomeado los permisos para que solo se vean los clientes agregados por el mismo agente , pero se siguen mostrando los clientes añadidos por otros agentes 

### PERMISOS
![permisos](https://user-images.githubusercontent.com/52018940/174902889-4d92bb1f-ba27-4125-a92a-377afa7d6989.png)

### Usuarios que debo de ver por que son añadidos por otros agentes
![agentes](https://user-images.githubusercontent.com/52018940/174902286-c84f0a00-d577-4dda-8ef8-80e15c21a64f.png)

2: Cuanto un producto tiene stock , no se muestra en  el punto de venta

### Stock añadido
![stock](https://user-images.githubusercontent.com/52018940/174902725-a3f64c8a-c344-4aa1-a5a8-7cbe59223b13.png)

### No se muestra el producto que tiene stock
![producto no encontrado](https://user-images.githubusercontent.com/52018940/174902798-286430eb-ef91-4641-8abb-47e76b66ce42.png)

Al parecer el código no está diferenciando una empresa de la otra  y no puede contar la cantidad de stock.

**Comment by jjosez** [comment]
1.- No esta implementado ver solamente los registros del usuario, si gustas puedes implementarlo con un plugin no lo implementare pronto, en mi caso ocupo que se muestren todos los clientes con cualquier usuario. 
Talvez lo implemente con una configuracion en las terminales, pero por el momento no.

2.- No esta probado con el plugin stock avanzado, lo reviso

**Comment by lmiguelm26** [comment]
Gracias
