### ISSUE TITLE
Recomendaciones 

### ISSUE THREAD

**Issue by lmiguelm26** [jjosez/POS#15]
Amigo excelente el plugin esta funcionando muy bien !!!

Algunas plus que pueden ser muy útiles:

1) poder modificar facturas ya generadas en caso de error de el cajero , ya que si se modifica directamente no se ve reflejado el cambio en el arqueo 

2) algunas tiendas tienen gastos mínimos durante el día , ejemplo compra de insumos como servilletas salsas etc .. se puede generar una factura negativa pero no se resta de el total esperado 

3) optimizar un poco los tickets ya que estos cuando hay variedad de productos son extremadamente largos . ( Prodia ser que se eligiera en la configuración de tickets un  ticket más resumido 

Ejemplo:
![image](https://user-images.githubusercontent.com/52018940/175988209-cb77f56d-017a-4735-8033-f824f431e887.png)

Muchas gracias!!!

**Comment by jjosez** [comment]
1.- Lo dejare pendiente.

2.- Ya agrege esa funcion en la version 1.96

2.- en la imagen esta mal el numero de caracteres, por eso se sale de la linea.
